image: Visual Studio 2017
version: 0.6.6-{build}
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
clone_depth: 10
before_build:
  - appveyor-retry dotnet restore -v Minimal yaap.sln
build_script:
  - dotnet build -c release
  - dotnet build -c debug
after_build:
  - dotnet pack "Yaap" -c release
test:
  assemblies:
    #- Yaap.Tests\bin\Debug\net471\Yaap.Tests.dll
    - Yaap.Tests\bin\Debug\netcoreapp2.0\Yaap.Tests.dll
artifacts:
  - path: 'Yaap\bin\release\*.nupkg'
    name: Nuget
deploy:
#  - provider: Environment
#    name: MyGet Unstable
#    on:
#      deploy_myget_unstable: true
#  - provider: Environment
#    name: MyGet Stable
#    on:
#      deploy_myget_stable: true
#  - provider: Environment
#    name: Npgsql Github
#    on:
#      deploy_github_release: true
